export enum FIELD_TYPE {
  DROPDOWN = 'DROPDOWN',
  TEXTBOX = 'TEXTBOX',
  DATE_PICKER = 'DATE_PICKER',
}

export enum ACTION_NAME {
  UPDATE_POLICY_CREATED_AT = 'UPDATE_POLICY_CREATED_AT',
  UPDATE_COMPANY_NAME = 'UPDATE_COMPANY_NAME',
  UPDATE_COMPANY_AGENT_NAME = 'UPDATE_COMPANY_AGENT_NAME',
  UPDATE_POLICY_NUMBER = 'UPDATE_POLICY_NUMBER',
  UPDATE_CUSTOMER_NAME = 'UPDATE_CUSTOMER_NAME',
  UPDATE_CONTACT_NUMBER = 'UPDATE_CONTACT_NUMBER',
  UPDATE_INSURER_NAME = 'UPDATE_INSURER_NAME',
  UPDATE_VEHICLE_NUMBER = 'UPDATE_VEHICLE_NUMBER',
  UPDATE_INSURED_DECLARED_VALUE = 'UPDATE_INSURED_DECLARED_VALUE',
  UPDATE_OWN_DAMAGE_VALUE = 'UPDATE_OWN_DAMAGE_VALUE',
  UPDATE_POLICY_TOTAL_VALUE = 'UPDATE_POLICY_TOTAL_VALUE',
  UPDATE_POLICY_DUE_DATE = 'UPDATE_POLICY_DUE_DATE',
  UPDATE_REFERENCE = 'UPDATE_REFERENCE',
  UPDATE_DISCOUNT_PROVIDED = 'UPDATE_DISCOUNT_PROVIDED',
  UPDATE_MODE_OF_PAYMENT = 'UPDATE_MODE_OF_PAYMENT',
  UPDATE_REMARKS = 'UPDATE_REMARKS',
  UPDATE_PAYMENT_OUT = 'UPDATE_PAYMENT_OUT',
  UPDATE_PAYMENT_OUT_MEMBER_NAME = 'UPDATE_PAYMENT_OUT_MEMBER_NAME',
  UPDATE_LIST = 'UPDATE_LIST'
}

export enum INSURANCE_KEYS {
  POLICY_CREATED_AT = 'policyCreatedAt',
  COMPANY_NAME = 'companyName',
  COMPANY_AGENT_NAME = 'companyAgentName',
  POLICY_NUMBER = 'policyNumber',
  CUSTOMER_NAME = 'customerName',
  CONTACT_NUMBER = 'contactNumber',
  INSURER_NAME = 'insurerName',
  VEHICLE_NUMBER = 'vehicleNumber',
  INSURED_DECLARED_VALUE = 'insuredDeclaredValue',
  OWN_DAMAGE_VALUE = 'ownDamageValue',
  POLICY_TOTAL_VALUE = 'policyTotalValue',
  POLICY_DUE_DATE = 'policyDueDate',
  REFERENCE = 'reference',
  DISCOUNT_PROVIDED = 'discountProvided',
  MODE_OF_PAYMENT = 'modeOfPayment',
  REMARKS = 'remarks',
  PAYMENT_OUT = 'paymentOut',
  PAYMENT_OUT_MEMBER_NAME = 'paymentOutMemberName',
}

export const INITIAL_DATA_STATE: IStateElement[] = [
  {
    key: INSURANCE_KEYS.POLICY_CREATED_AT,
    value: new Date().toISOString(),
    fieldType: FIELD_TYPE.DATE_PICKER,
    defaultValue: '',
    label: 'Policy Date',
    actionName: ACTION_NAME.UPDATE_POLICY_CREATED_AT,
    valueType: 'string',
    isRequired: true,
    regex: '',
    error: '',
  },
  {
    key: INSURANCE_KEYS.COMPANY_NAME,
    fieldType: FIELD_TYPE.TEXTBOX,
    value: '',
    defaultValue: '',
    label: 'Company Name',
    actionName: ACTION_NAME.UPDATE_COMPANY_NAME,
    valueType: 'string',
    isRequired: true,
    regex: '',
    error: '',
  },
  {
    key: INSURANCE_KEYS.COMPANY_AGENT_NAME,
    fieldType: FIELD_TYPE.TEXTBOX,
    value: '',
    defaultValue: '',
    label: 'Agent Registered',
    actionName: ACTION_NAME.UPDATE_COMPANY_AGENT_NAME,
    valueType: 'string',
    isRequired: true,
    regex: '',
    error: '',
  },
  {
    key: INSURANCE_KEYS.POLICY_NUMBER,
    fieldType: FIELD_TYPE.TEXTBOX,
    value: '',
    defaultValue: '',
    label: 'Policy Number',
    actionName: ACTION_NAME.UPDATE_POLICY_NUMBER,
    valueType: 'string',
    isRequired: true,
    regex: '',
    error: '',
  },
  {
    key: INSURANCE_KEYS.CUSTOMER_NAME,
    fieldType: FIELD_TYPE.TEXTBOX,
    value: '',
    defaultValue: '',
    label: 'Customer Name',
    actionName: ACTION_NAME.UPDATE_CUSTOMER_NAME,
    valueType: 'string',
    isRequired: true,
    regex: '',
    error: '',
  },
  {
    key: INSURANCE_KEYS.CONTACT_NUMBER,
    fieldType: FIELD_TYPE.TEXTBOX,
    value: '',
    defaultValue: '',
    label: 'Contact Number',
    actionName: ACTION_NAME.UPDATE_CONTACT_NUMBER,
    valueType: 'string',
    isRequired: true,
    regex: '',
    error: '',
  },
  {
    key: INSURANCE_KEYS.INSURER_NAME,
    fieldType: FIELD_TYPE.TEXTBOX,
    value: '',
    defaultValue: '',
    label: 'Insurer Name',
    actionName: ACTION_NAME.UPDATE_INSURER_NAME,
    valueType: 'string',
    isRequired: true,
    regex: '',
    error: '',
  },
  {
    key: INSURANCE_KEYS.VEHICLE_NUMBER,
    fieldType: FIELD_TYPE.TEXTBOX,
    value: '',
    defaultValue: '',
    label: 'Vehicle Number',
    actionName: ACTION_NAME.UPDATE_VEHICLE_NUMBER,
    valueType: 'string',
    isRequired: true,
    regex: '',
    error: '',
  },
  {
    key: INSURANCE_KEYS.INSURED_DECLARED_VALUE,
    fieldType: FIELD_TYPE.TEXTBOX,
    value: '',
    defaultValue: '',
    label: 'IDV',
    actionName: ACTION_NAME.UPDATE_INSURED_DECLARED_VALUE,
    valueType: 'number',
    isRequired: true,
    regex: '',
    error: '',
  },
  {
    key: INSURANCE_KEYS.OWN_DAMAGE_VALUE,
    fieldType: FIELD_TYPE.TEXTBOX,
    value: '',
    defaultValue: '',
    label: 'OD',
    actionName: ACTION_NAME.UPDATE_OWN_DAMAGE_VALUE,
    valueType: 'number',
    isRequired: true,
    regex: '',
    error: '',
  },
  {
    key: INSURANCE_KEYS.POLICY_TOTAL_VALUE,
    fieldType: FIELD_TYPE.TEXTBOX,
    value: '',
    defaultValue: '',
    label: 'Total Amount',
    actionName: ACTION_NAME.UPDATE_POLICY_TOTAL_VALUE,
    valueType: 'number',
    isRequired: true,
    regex: '',
    error: '',
  },
  {
    key: INSURANCE_KEYS.MODE_OF_PAYMENT,
    fieldType: FIELD_TYPE.TEXTBOX,
    value: '',
    defaultValue: '',
    label: 'Mode Of Payment',
    actionName: ACTION_NAME.UPDATE_MODE_OF_PAYMENT,
    valueType: 'string',
    isRequired: true,
    regex: '',
     error: '',
  },
  {
    key: INSURANCE_KEYS.POLICY_DUE_DATE,
    fieldType: FIELD_TYPE.DATE_PICKER,
    value: new Date(new Date().setFullYear(new Date().getFullYear() + 1)).toISOString(),
    defaultValue: '',
    label: 'Due Date',
    actionName: ACTION_NAME.UPDATE_POLICY_DUE_DATE,
    valueType: 'string',
    isRequired: true,
    regex: '',
    error: '',
  },
  {
    key: INSURANCE_KEYS.REFERENCE,
    fieldType: FIELD_TYPE.TEXTBOX,
    value: '',
    defaultValue: '',
    label: 'Reference',
    actionName: ACTION_NAME.UPDATE_REFERENCE,
    valueType: 'string',
    isRequired: false,
    regex: '',
    error: '',
  },
  {
    key: INSURANCE_KEYS.DISCOUNT_PROVIDED,
    fieldType: FIELD_TYPE.TEXTBOX,
    value: '',
    defaultValue: '',
    label: 'Discount Value',
    actionName: ACTION_NAME.UPDATE_DISCOUNT_PROVIDED,
    valueType: 'number',
    isRequired: false,
    regex: '',
    error: '',
  },
  {
    key: INSURANCE_KEYS.REMARKS,
    fieldType: FIELD_TYPE.TEXTBOX,
    value: '',
    defaultValue: '',
    label: 'Remarks',
    actionName: ACTION_NAME.UPDATE_REMARKS,
    valueType: 'string',
    isRequired: false,
    regex: '',
     error: '',
  },
  {
    key: INSURANCE_KEYS.PAYMENT_OUT,
    fieldType: FIELD_TYPE.TEXTBOX,
    value: '',
    defaultValue: '',
    label: 'Payment Out',
    actionName: ACTION_NAME.UPDATE_PAYMENT_OUT,
    valueType: 'number',
    isRequired: false,
    regex: '',
     error: '',
  },
  {
    key: INSURANCE_KEYS.PAYMENT_OUT_MEMBER_NAME,
    fieldType: FIELD_TYPE.TEXTBOX,
    value: '',
    defaultValue: '',
    label: 'Payment Out Member',
    actionName: ACTION_NAME.UPDATE_PAYMENT_OUT_MEMBER_NAME,
    valueType: 'string',
    isRequired: false,
    regex: '',
     error: '',
  },
];
